"use client";
import { useState, type FormEvent } from "react";
const initial = { name: "", email: "", school: "", subject: "", message: "" };
export function ContactForm() {
 const [form, setForm] = useState(initial); const [status, setStatus] = useState<"idle"|"sending"|"success"|"error">("idle"); const [message, setMessage] = useState("");
 const update = (key: keyof typeof form, value: string) => setForm(current => ({ ...current, [key]: value }));
 async function submit(event: FormEvent) { event.preventDefault(); setStatus("sending"); setMessage(""); try { const response = await fetch("/api/contact", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Unable to send your message."); setStatus("success"); setMessage(data.message); setForm(initial); } catch (error) { setStatus("error"); setMessage(error instanceof Error ? error.message : "Unable to send your message."); } }
 return <form onSubmit={submit} className="space-y-5" noValidate>
  <div><label htmlFor="contact-name" className="block text-sm font-medium text-navy mb-1.5">Full name</label><input id="contact-name" required value={form.name} onChange={e=>update("name",e.target.value)} type="text" autoComplete="name" className="w-full h-11 px-4 rounded-md border border-border bg-white text-sm focus:outline-none focus:border-navy focus:ring-1 focus:ring-navy" /></div>
  <div><label htmlFor="contact-email" className="block text-sm font-medium text-navy mb-1.5">Email</label><input id="contact-email" required value={form.email} onChange={e=>update("email",e.target.value)} type="email" autoComplete="email" className="w-full h-11 px-4 rounded-md border border-border bg-white text-sm focus:outline-none focus:border-navy focus:ring-1 focus:ring-navy" /></div>
  <div><label htmlFor="contact-school" className="block text-sm font-medium text-navy mb-1.5">School <span className="font-normal text-charcoal-light">(optional)</span></label><input id="contact-school" value={form.school} onChange={e=>update("school",e.target.value)} type="text" autoComplete="organization" className="w-full h-11 px-4 rounded-md border border-border bg-white text-sm focus:outline-none focus:border-navy focus:ring-1 focus:ring-navy" /></div>
  <div><label htmlFor="contact-subject" className="block text-sm font-medium text-navy mb-1.5">How can we help?</label><select id="contact-subject" required value={form.subject} onChange={e=>update("subject",e.target.value)} className="w-full h-11 px-4 rounded-md border border-border bg-white text-sm focus:outline-none focus:border-navy focus:ring-1 focus:ring-navy"><option value="">Select a subject</option><option value="consultancy">English Department Consultancy</option><option value="pd">Professional Development</option><option value="ai">AI Platform</option><option value="general">General Inquiry</option></select></div>
  <div><label htmlFor="contact-message" className="block text-sm font-medium text-navy mb-1.5">Message</label><textarea id="contact-message" required minLength={10} value={form.message} onChange={e=>update("message",e.target.value)} rows={5} className="w-full px-4 py-3 rounded-md border border-border bg-white text-sm focus:outline-none focus:border-navy focus:ring-1 focus:ring-navy resize-none" /></div>
  {status !== "idle" && <p role="status" className={status === "success" ? "text-sm text-success" : "text-sm text-error"}>{message}</p>}
  <button disabled={status === "sending"} type="submit" className="w-full h-12 bg-navy text-white font-semibold rounded-lg hover:bg-navy-light disabled:opacity-60 transition-all">{status === "sending" ? "Sending…" : "Send message"}</button>
 </form>;
}
